# ruff: noqa: E501
"""Application-facing persistence repository contracts."""
from datetime import datetime
from typing import Protocol

from app.application.ports.market_data import SourceRecord
from app.application.ports.storage import SourceArtifactMetadata
from app.domain.governance.provenance import Provenance
from app.domain.market_data.corporate_actions import CorporateAction
from app.domain.market_data.identifiers import SourceIdentity
from app.domain.market_data.observations import MarketObservation
from app.domain.reference_data.reference import IdentifierMapping, Listing, Security


class SecurityRepositoryPort(Protocol):
    def get(self, security_id: str) -> Security | None: ...
    def save(self, security: Security) -> None: ...
class ListingRepositoryPort(Protocol):
    def get(self, listing_id: str) -> Listing | None: ...
    def save(self, listing: Listing) -> None: ...
class IdentifierMappingRepositoryPort(Protocol):
    def find(self, provider_id: str, external_identifier: str) -> IdentifierMapping | None: ...
    def save(self, mapping: IdentifierMapping) -> None: ...
class MarketObservationRepositoryPort(Protocol):
    def save(self, observation: MarketObservation) -> None: ...
    def find_existing(self, observation: MarketObservation) -> MarketObservation | None: ...
    def get_by_listing_and_period(
        self, listing_id: str, start: datetime, end: datetime
    ) -> tuple[MarketObservation, ...]: ...
    def get_as_of(
        self, listing_id: str, observed_at: datetime, available_at: datetime
    ) -> tuple[MarketObservation, ...]: ...
class CorporateActionRepositoryPort(Protocol):
    def save(self, action: CorporateAction) -> None: ...
    def get_by_listing_and_period(
        self, listing_id: str, start: datetime, end: datetime
    ) -> tuple[CorporateAction, ...]: ...
class SourceRecordRepositoryPort(Protocol):
    def save(self, record: SourceRecord) -> None: ...
    def find_by_source_identity(self, identity: SourceIdentity) -> SourceRecord | None: ...
class SourceArtifactRepositoryPort(Protocol):
    def save(self, artifact: SourceArtifactMetadata) -> None: ...
    def get(self, artifact_id: str) -> SourceArtifactMetadata | None: ...
class ProvenanceRepositoryPort(Protocol):
    def save(self, provenance: Provenance) -> None: ...
    def get(self, provenance_id: str) -> Provenance | None: ...
